[project]
name = "ahmaedinfo"
version = "1.1.7"
description = "AHMAEDINFO API Wrapper"
readme = "README.md"
authors = [
    { name = "Ahmed" }
]
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = ["requests"]

keywords = ["api", "wrapper", "ahmaedinfo", "chatbot", "ai"]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

# ğŸ”¥ Ø±ÙˆØ§Ø¨Ø· Ù…Ù‡Ù…Ø© ØªØ¸Ù‡Ø± ÙÙŠ PyPI
[project.urls]
Homepage = "https://github.com/Ahmeadinfo/Ahmaedinfo"
Repository = "https://github.com/Ahmeadinfo/Ahmaedinfo"
Issues = "https://github.com/Ahmeadinfo/Ahmaedinfo/issues"

# Ù†Ø¸Ø§Ù… Ø§Ù„Ø¨Ù†Ø§Ø¡
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª setuptools
[tool.setuptools]
packages = ["ahmaedinfo"]

# Ø¬Ø¹Ù„ setuptools ÙŠØ³ØªØ·ÙŠØ¹ Ø§Ù„Ø¹Ø«ÙˆØ± Ø¹Ù„Ù‰ Ø§Ù„Ø¨Ø§ÙƒØ¯Ø¬
[tool.setuptools.packages.find]
where = ["."]
include = ["ahmaedinfo"]
